default_platform(:ios)

platform :ios do
  desc "Initializes the app on Apple Developer Portal and App Store Connect"
  lane :init_app do
    produce(
      app_name: "Missions - Vicente Tasks",
      language: "en-US",
      app_version: "1.0",
      sku: "com.vicente.missions"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure correct version bumping
    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"]
    )

    # Build the application
    build_app(
      scheme: "Missions",
      export_method: "app-store"
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
