name: Deploy to TestFlight

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup Fastlane App Store Connect API Key
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}" > AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
        working-directory: ./Missions/fastlane

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: fastlane beta
        working-directory: ./Missions
